site_name: CTF Writeups
site_description: Personal archive of CTF challenges and solutions
site_author: zeba
repo_url: https://github.com/ZebaLive/ctf-writeups
repo_name: ZebaLive/ctf-writeups

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true

nav:
  - Home: index.md
  - 2025:
    - Mārtiņa-CTF:
        - Overview: 2025/martina-ctf/README.md
        - Web:
            - Possibly secure 2003 webapp: 2025/martina-ctf/web/possibly-secure-2003-webapp/writeup.md
        - Misc:
            - Rewritten History: 2025/martina-ctf/misc/rewritten-history/writeup.md
    - ECSC:
        - Overview: 2025/ecsc/README.md
        - Web:
            - Flag Szop: 2025/ecsc/web/flag-szop/writeup.md
        - Misc:
            - Blue Mouse: 2025/ecsc/misc/blue-mouse/writeup.md
    - openECSC:
        - Overview: 2025/openecsc/README.md
        - Web:
            - kittychat: 2025/openecsc/web/kittychat/writeup.md
            - eventhub: 2025/openecsc/web/eventhub/writeup.md
            - kv-messenger: 2025/openecsc/web/kv-messenger/writeup.md
            - polish-bar: 2025/openecsc/web/polish-bar/writeup.md
        - Crypto:
            - polite-email: 2025/openecsc/crypto/polite-email/writeup.md
        - PWN:
            - cfp: 2025/openecsc/pwn/cfp/writeup.md
        - Stego:
            - calamansi: 2025/openecsc/stego/calamansi/writeup.md
        - Misc:
            - oci: 2025/openecsc/misc/oci/writeup.md
            - ruby-matcher: 2025/openecsc/misc/ruby-matcher/writeup.md
            - organization: 2025/openecsc/misc/organization/writeup.md
     